;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Enemy.Attack",DevComment="")
+GameplayTagList=(Tag="Enemy.HearSound",DevComment="")
+GameplayTagList=(Tag="Enemy.PlayerDetected",DevComment="")
+GameplayTagList=(Tag="Enemy.PlayerLost",DevComment="")
+GameplayTagList=(Tag="Enemy.StunEndedChase",DevComment="")
+GameplayTagList=(Tag="Enemy.StunEndedIdle",DevComment="")
+GameplayTagList=(Tag="Enemy.Stunned",DevComment="")
+GameplayTagList=(Tag="Player.Ability.Obscura",DevComment="")
+GameplayTagList=(Tag="Player.Key.Shift",DevComment="")
+GameplayTagList=(Tag="Player.State.Dialogue",DevComment="")
+GameplayTagList=(Tag="Player.State.Stun",DevComment="")

